-- ==================================================
-- 基础会员套餐
-- ==================================================

-- 基础会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('basic_month', '基础会员', '税务知识入门用户', 'month', 9.9, 19.9, 30, 30, 3, 50, 512, 50, TRUE, FALSE, FALSE, 'active', 0, '{"level": "basic", "priority": 1, "enable_invoice_penetration": false, "max_invoice_penetration": 0, "enable_panorama": false, "max_panorama": 0, "enable_business_risk": false, "max_business_risk": 0}'::jsonb, '[{"title": "基础问答", "desc": "税务知识基础问答"}, {"title": "政策查询", "desc": "基础政策查询功能"}, {"title": "AI咨询", "desc": "30次/月AI咨询"}, {"title": "3个知识库", "desc": "支持创建3个个人知识库"}, {"title": "512MB存储", "desc": "云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- 基础会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('basic_year', '基础会员年卡', '税务知识入门用户年费版，性价比更高', 'year', 99, 118.8, 365, 50, 5, 100, 1024, 100, TRUE, FALSE, FALSE, 'active', 0, '{"level": "basic", "priority": 1, "enable_invoice_penetration": true, "max_invoice_penetration": 3, "enable_panorama": false, "max_panorama": 0, "enable_business_risk": false, "max_business_risk": 0}'::jsonb, '[{"title": "基础问答", "desc": "税务知识基础问答"}, {"title": "政策查询", "desc": "基础政策查询功能"}, {"title": "AI咨询", "desc": "50次/月AI咨询"}, {"title": "5个知识库", "desc": "支持创建5个个人知识库"}, {"title": "1GB存储", "desc": "云端文件存储空间"}, {"title": "发票穿透", "desc": "每月3次发票穿透分析"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V1铂金会员套餐
-- ==================================================

-- V1铂金会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v1_platinum_month', 'V1铂金会员', '个体工商户/自由职业者', 'month', 69, 89, 30, -1, 10, 500, 2048, 200, TRUE, TRUE, FALSE, 'active', 0, '{"level": "v1_platinum", "priority": 2, "enable_invoice_penetration": true, "max_invoice_penetration": 20, "enable_panorama": true, "max_panorama": 5, "enable_business_risk": true, "max_business_risk": 5}'::jsonb, '[{"title": "进项发票验真", "desc": "自动验真进项发票"}, {"title": "简易计税", "desc": "支持简易计税方法计算"}, {"title": "申报指引", "desc": "智能税务申报指引"}, {"title": "无限对话", "desc": "每日无限制AI对话"}, {"title": "网络搜索", "desc": "实时网络搜索功能"}, {"title": "发票穿透", "desc": "每月20次发票穿透分析"}, {"title": "全景报告", "desc": "每月5次企业全景报告"}, {"title": "经营风险", "desc": "每月5次经营风险评估"}, {"title": "2GB存储", "desc": "云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- V1铂金会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v1_platinum_year', 'V1铂金会员年卡', '个体工商户/自由职业者年费版', 'year', 698, 828, 365, -1, 15, 1000, 4096, 400, TRUE, TRUE, FALSE, 'active', 0, '{"level": "v1_platinum", "priority": 2, "enable_invoice_penetration": true, "max_invoice_penetration": 50, "enable_panorama": true, "max_panorama": 15, "enable_business_risk": true, "max_business_risk": 15}'::jsonb, '[{"title": "进项发票验真", "desc": "自动验真进项发票"}, {"title": "简易计税", "desc": "支持简易计税方法计算"}, {"title": "申报指引", "desc": "智能税务申报指引"}, {"title": "无限对话", "desc": "每日无限制AI对话"}, {"title": "网络搜索", "desc": "实时网络搜索功能"}, {"title": "发票穿透", "desc": "每月50次发票穿透分析"}, {"title": "全景报告", "desc": "每月15次企业全景报告"}, {"title": "经营风险", "desc": "每月15次经营风险评估"}, {"title": "4GB存储", "desc": "云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V2黄金会员套餐
-- ==================================================

-- V2黄金会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v2_gold_month', 'V2黄金会员', '中小网红/电商主播', 'month', 199, 259, 30, -1, 20, 2000, 5120, 500, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v2_gold", "priority": 3, "enable_invoice_penetration": true, "max_invoice_penetration": 50, "enable_panorama": true, "max_panorama": 20, "enable_business_risk": true, "max_business_risk": 20, "enable_contract_analysis": true}'::jsonb, '[{"title": "个税优化", "desc": "智能个税优化方案"}, {"title": "合规审计", "desc": "税务合规自动审计"}, {"title": "稽查应对", "desc": "税务稽查应对指引"}, {"title": "合同解析", "desc": "合同涉税条款解析（≤20页）"}, {"title": "网红佣金计税", "desc": "网红佣金智能计税"}, {"title": "全功能解锁", "desc": "RAG+网络搜索+MCP工具"}, {"title": "发票穿透", "desc": "每月50次发票穿透分析"}, {"title": "全景报告", "desc": "每月20次企业全景报告"}, {"title": "经营风险", "desc": "每月20次经营风险评估"}, {"title": "5GB存储", "desc": "云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- V2黄金会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v2_gold_year', 'V2黄金会员年卡', '中小网红/电商主播年费版', 'year', 1980, 2388, 365, -1, 30, 5000, 10240, 1000, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v2_gold", "priority": 3, "enable_invoice_penetration": true, "max_invoice_penetration": 100, "enable_panorama": true, "max_panorama": 50, "enable_business_risk": true, "max_business_risk": 50, "enable_contract_analysis": true}'::jsonb, '[{"title": "个税优化", "desc": "智能个税优化方案"}, {"title": "合规审计", "desc": "税务合规自动审计"}, {"title": "稽查应对", "desc": "税务稽查应对指引"}, {"title": "合同解析", "desc": "合同涉税条款解析（≤20页）"}, {"title": "网红佣金计税", "desc": "网红佣金智能计税"}, {"title": "全功能解锁", "desc": "RAG+网络搜索+MCP工具"}, {"title": "发票穿透", "desc": "每月100次发票穿透分析"}, {"title": "全景报告", "desc": "每月50次企业全景报告"}, {"title": "经营风险", "desc": "每月50次经营风险评估"}, {"title": "10GB存储", "desc": "云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V3钻石会员套餐
-- ==================================================

-- V3钻石会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v3_diamond_month', 'V3钻石会员', '中小微企业', 'month', 999, 1299, 30, -1, 50, 10000, 20480, 2000, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v3_diamond", "priority": 4, "enable_invoice_penetration": true, "max_invoice_penetration": 100, "enable_panorama": true, "max_panorama": 50, "enable_business_risk": true, "max_business_risk": 50, "enable_tax_planning": true, "enable_mock_audit": true}'::jsonb, '[{"title": "全税种管理", "desc": "支持所有税种管理"}, {"title": "发票穿透", "desc": "深度发票关联分析"}, {"title": "风险扫描", "desc": "税务风险自动扫描"}, {"title": "税务筹划", "desc": "智能税务筹划方案生成"}, {"title": "模拟稽查", "desc": "模拟税务稽查演练"}, {"title": "全功能解锁", "desc": "RAG+网络搜索+MCP工具"}, {"title": "发票穿透", "desc": "每月100次发票穿透分析"}, {"title": "全景报告", "desc": "每月50次企业全景报告"}, {"title": "经营风险", "desc": "每月50次经营风险评估"}, {"title": "20GB存储", "desc": "超大云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- V3钻石会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v3_diamond_year', 'V3钻石会员年卡', '中小微企业年费版', 'year', 9980, 11988, 365, -1, 100, 20000, 51200, 5000, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v3_diamond", "priority": 4, "enable_invoice_penetration": true, "max_invoice_penetration": 200, "enable_panorama": true, "max_panorama": 100, "enable_business_risk": true, "max_business_risk": 100, "enable_tax_planning": true, "enable_mock_audit": true}'::jsonb, '[{"title": "全税种管理", "desc": "支持所有税种管理"}, {"title": "发票穿透", "desc": "深度发票关联分析"}, {"title": "风险扫描", "desc": "税务风险自动扫描"}, {"title": "税务筹划", "desc": "智能税务筹划方案生成"}, {"title": "模拟稽查", "desc": "模拟税务稽查演练"}, {"title": "全功能解锁", "desc": "RAG+网络搜索+MCP工具"}, {"title": "发票穿透", "desc": "每月200次发票穿透分析"}, {"title": "全景报告", "desc": "每月100次企业全景报告"}, {"title": "经营风险", "desc": "每月100次经营风险评估"}, {"title": "50GB存储", "desc": "超大云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V4黑金会员套餐
-- ==================================================

-- V4黑金会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v4_black_gold_year', 'V4黑金会员', '数商行业企业', 'year', 19800, 23760, 365, -1, 200, 50000, 102400, 10000, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v4_black_gold", "priority": 5, "enable_invoice_penetration": true, "max_invoice_penetration": -1, "enable_panorama": true, "max_panorama": -1, "enable_business_risk": true, "max_business_risk": -1, "enable_tax_planning": true, "enable_mock_audit": true, "enable_enterprise_diagnosis": true, "enable_digital_compliance": true, "enable_strategic_planning": true}'::jsonb, '[{"title": "税务架构设计", "desc": "企业税务架构顶层设计"}, {"title": "战略决策支持", "desc": "战略级税务决策支持"}, {"title": "企业诊断", "desc": "企业税务健康诊断"}, {"title": "数商合规", "desc": "数商行业合规方案"}, {"title": "战略规划", "desc": "企业税务战略规划"}, {"title": "全功能解锁", "desc": "RAG+网络搜索+MCP工具"}, {"title": "发票穿透", "desc": "无限次发票穿透分析"}, {"title": "全景报告", "desc": "无限次企业全景报告"}, {"title": "经营风险", "desc": "无限次经营风险评估"}, {"title": "税务筹划", "desc": "智能税务筹划方案"}, {"title": "模拟稽查", "desc": "模拟税务稽查演练"}, {"title": "专属顾问", "desc": "1对1专属税务顾问"}, {"title": "100GB存储", "desc": "超大云端文件存储空间"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;
