-- ==================================================
-- 基础会员套餐
-- ==================================================

-- 基础会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('basic_month', '基础会员', '税务知识入门用户', 'month', 9.9, 19.9, 30, 30, 0, 0, 0, 0, TRUE, FALSE, FALSE, 'active', 0, '{"level": "basic", "priority": 1, "daily_chat_limit": 30, "expert_followup_available": false, "quarterly_consultation_minutes": 0, "contract_screening_pages": 3, "ocr_invoice_monthly": 0, "multi_page_contract_pages": 0, "batch_api_available": false, "risk_indicators_count": 5, "risk_warnings_count": 0, "scenario_metrics_count": 0, "mock_audit_available": false, "enable_basic_calculator": true, "enable_tax_filing_generator": false, "enable_multi_platform_tax": false, "enable_agi_planning": false}'::jsonb, '[{"title": "AI税务咨询", "desc": "30次/月基础咨询"}, {"title": "合同筛查", "desc": "3页内合同筛查"}, {"title": "风险指标", "desc": "5项基础指标"}, {"title": "计算器", "desc": "基础计算器"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- 基础会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('basic_year', '基础会员年卡', '税务知识入门用户年费版', 'year', 99, 118.8, 365, 50, 0, 0, 0, 0, TRUE, FALSE, FALSE, 'active', 0, '{"level": "basic", "priority": 1, "daily_chat_limit": 50, "expert_followup_available": false, "quarterly_consultation_minutes": 0, "contract_screening_pages": 3, "ocr_invoice_monthly": 0, "multi_page_contract_pages": 0, "batch_api_available": false, "risk_indicators_count": 5, "risk_warnings_count": 0, "scenario_metrics_count": 0, "mock_audit_available": false, "enable_basic_calculator": true, "enable_tax_filing_generator": false, "enable_multi_platform_tax": false, "enable_agi_planning": false}'::jsonb, '[{"title": "AI税务咨询", "desc": "50次/月基础咨询"}, {"title": "合同筛查", "desc": "3页内合同筛查"}, {"title": "风险指标", "desc": "5项基础指标"}, {"title": "计算器", "desc": "基础计算器"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V1铂金会员套餐
-- ==================================================

-- V1铂金会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v1_platinum_month', 'V1铂金会员', '个体工商户/自由职业者', 'month', 69, 89, 30, -1, 0, 0, 0, 0, TRUE, TRUE, FALSE, 'active', 0, '{"level": "v1_platinum", "priority": 2, "daily_chat_limit": -1, "expert_followup_available": true, "expert_followup_monthly": 10, "quarterly_consultation_minutes": 0, "contract_screening_pages": 3, "ocr_invoice_monthly": 200, "multi_page_contract_pages": 0, "batch_api_available": false, "risk_indicators_count": 10, "risk_warnings_count": 10, "scenario_metrics_count": 0, "mock_audit_available": false, "enable_basic_calculator": true, "enable_tax_filing_generator": true, "enable_multi_platform_tax": false, "enable_agi_planning": false}'::jsonb, '[{"title": "AI税务咨询", "desc": "不限次+10次专家追问"}, {"title": "发票识别", "desc": "OCR发票识别200张/月"}, {"title": "风险预警", "desc": "10项风险预警"}, {"title": "申报生成", "desc": "经营所得税申报生成"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- V1铂金会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v1_platinum_year', 'V1铂金会员年卡', '个体工商户/自由职业者年费版', 'year', 698, 828, 365, -1, 0, 0, 0, 0, TRUE, TRUE, FALSE, 'active', 0, '{"level": "v1_platinum", "priority": 2, "daily_chat_limit": -1, "expert_followup_available": true, "expert_followup_monthly": 20, "quarterly_consultation_minutes": 0, "contract_screening_pages": 3, "ocr_invoice_monthly": 200, "multi_page_contract_pages": 0, "batch_api_available": false, "risk_indicators_count": 10, "risk_warnings_count": 10, "scenario_metrics_count": 0, "mock_audit_available": false, "enable_basic_calculator": true, "enable_tax_filing_generator": true, "enable_multi_platform_tax": false, "enable_agi_planning": false}'::jsonb, '[{"title": "AI税务咨询", "desc": "不限次+20次专家追问"}, {"title": "发票识别", "desc": "OCR发票识别200张/月"}, {"title": "风险预警", "desc": "10项风险预警"}, {"title": "申报生成", "desc": "经营所得税申报生成"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V2黄金会员套餐
-- ==================================================

-- V2黄金会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v2_gold_month', 'V2黄金会员', '中小网红/电商主播', 'month', 199, 259, 30, -1, 0, 0, 0, 0, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v2_gold", "priority": 3, "daily_chat_limit": -1, "expert_followup_available": true, "expert_followup_monthly": 20, "quarterly_consultation_minutes": 90, "contract_screening_pages": 3, "ocr_invoice_monthly": 200, "multi_page_contract_pages": 50, "batch_api_available": false, "risk_indicators_count": 20, "risk_warnings_count": 20, "scenario_metrics_count": 20, "mock_audit_available": true, "enable_basic_calculator": true, "enable_tax_filing_generator": true, "enable_multi_platform_tax": true, "enable_agi_planning": false}'::jsonb, '[{"title": "AI税务咨询", "desc": "不限次+季度1对1咨询90分钟"}, {"title": "合同审查", "desc": "多页合同审查50页/次"}, {"title": "稽查模拟", "desc": "模拟税务稽查演练"}, {"title": "计税模型", "desc": "多平台收入计税模型"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- V2黄金会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v2_gold_year', 'V2黄金会员年卡', '中小网红/电商主播年费版', 'year', 1980, 2388, 365, -1, 0, 0, 0, 0, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v2_gold", "priority": 3, "daily_chat_limit": -1, "expert_followup_available": true, "expert_followup_monthly": 30, "quarterly_consultation_minutes": 180, "contract_screening_pages": 3, "ocr_invoice_monthly": 500, "multi_page_contract_pages": 50, "batch_api_available": false, "risk_indicators_count": 20, "risk_warnings_count": 20, "scenario_metrics_count": 20, "mock_audit_available": true, "enable_basic_calculator": true, "enable_tax_filing_generator": true, "enable_multi_platform_tax": true, "enable_agi_planning": false}'::jsonb, '[{"title": "AI税务咨询", "desc": "不限次+季度1对1咨询180分钟"}, {"title": "发票识别", "desc": "OCR发票识别500张/月"}, {"title": "合同审查", "desc": "多页合同审查50页/次"}, {"title": "稽查模拟", "desc": "模拟税务稽查演练"}, {"title": "计税模型", "desc": "多平台收入计税模型"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V3钻石会员套餐
-- ==================================================

-- V3钻石会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v3_diamond_month', 'V3钻石会员', '中小微企业', 'month', 999, 1299, 30, -1, 0, 0, 0, 0, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v3_diamond", "priority": 4, "daily_chat_limit": -1, "expert_followup_available": true, "expert_followup_monthly": -1, "quarterly_consultation_minutes": 60, "dedicated_team_available": false, "contract_screening_pages": -1, "ocr_invoice_monthly": -1, "multi_page_contract_pages": 50, "batch_api_available": true, "batch_api_monthly_quota": 1000, "historical_data_retention_months": 6, "risk_indicators_count": 50, "risk_warnings_count": -1, "scenario_metrics_count": 50, "mock_audit_available": true, "risk_assessment_available": true, "enable_basic_calculator": true, "enable_tax_filing_generator": true, "enable_multi_platform_tax": true, "enable_agi_planning": true}'::jsonb, '[{"title": "AI税务咨询", "desc": "不限次+不限次专家追问"}, {"title": "专属顾问", "desc": "季度1对1咨询60分钟"}, {"title": "批量处理", "desc": "批量API对接1000次/月"}, {"title": "数据回溯", "desc": "6个月历史数据回溯"}, {"title": "风险监控", "desc": "50+全维度监控"}, {"title": "税务筹划", "desc": "全税种智能管理"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- V3钻石会员年卡
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v3_diamond_year', 'V3钻石会员年卡', '中小微企业年费版', 'year', 9980, 11988, 365, -1, 0, 0, 0, 0, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v3_diamond", "priority": 4, "daily_chat_limit": -1, "expert_followup_available": true, "expert_followup_monthly": -1, "quarterly_consultation_minutes": 120, "dedicated_team_available": false, "contract_screening_pages": -1, "ocr_invoice_monthly": -1, "multi_page_contract_pages": 100, "batch_api_available": true, "batch_api_monthly_quota": 5000, "historical_data_retention_months": 12, "risk_indicators_count": 50, "risk_warnings_count": -1, "scenario_metrics_count": 50, "mock_audit_available": true, "risk_assessment_available": true, "enable_basic_calculator": true, "enable_tax_filing_generator": true, "enable_multi_platform_tax": true, "enable_agi_planning": true}'::jsonb, '[{"title": "AI税务咨询", "desc": "不限次+不限次专家追问"}, {"title": "专属顾问", "desc": "季度1对1咨询120分钟"}, {"title": "批量处理", "desc": "批量API对接5000次/月"}, {"title": "数据回溯", "desc": "12个月历史数据回溯"}, {"title": "风险监控", "desc": "50+全维度监控"}, {"title": "税务筹划", "desc": "全税种智能管理"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;


-- ==================================================
-- V4黑金会员套餐
-- ==================================================

-- V4黑金会员
INSERT INTO business.member_packages (package_id, name, description, package_type, price, original_price, duration_days, max_daily_chats, max_kb_count, max_kb_documents, max_file_storage_mb, max_file_count, enable_rag, enable_web_search, enable_mcp_tools, status, sort_order, custom_config, benefits)
VALUES ('v4_black_gold_year', 'V4黑金会员', '数商行业企业', 'year', 19800, 23760, 365, -1, 0, 0, 0, 0, TRUE, TRUE, TRUE, 'active', 0, '{"level": "v4_black_gold", "priority": 5, "daily_chat_limit": -1, "expert_followup_available": true, "expert_followup_monthly": -1, "quarterly_consultation_minutes": 240, "dedicated_team_available": true, "dedicated_team_members": 3, "contract_screening_pages": -1, "ocr_invoice_monthly": -1, "multi_page_contract_pages": -1, "batch_api_available": true, "batch_api_monthly_quota": -1, "historical_data_retention_months": 36, "risk_indicators_count": 100, "risk_warnings_count": -1, "scenario_metrics_count": 100, "mock_audit_available": true, "risk_assessment_available": true, "real_time_monitoring": true, "enable_basic_calculator": true, "enable_tax_filing_generator": true, "enable_multi_platform_tax": true, "enable_agi_planning": true, "strategic_planning_available": true}'::jsonb, '[{"title": "AI税务咨询", "desc": "不限次+不限次专家追问"}, {"title": "专属团队", "desc": "3人专属团队服务"}, {"title": "1对1咨询", "desc": "季度1对1咨询240分钟"}, {"title": "批量处理", "desc": "批量API对接无限次"}, {"title": "数据回溯", "desc": "36个月历史数据回溯"}, {"title": "实时监控", "desc": "实时风险监控"}, {"title": "税务筹划", "desc": "AGI战略筹划"}]'::jsonb)
ON CONFLICT (package_id) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, package_type = EXCLUDED.package_type, price = EXCLUDED.price, original_price = EXCLUDED.original_price, duration_days = EXCLUDED.duration_days, max_daily_chats = EXCLUDED.max_daily_chats, max_kb_count = EXCLUDED.max_kb_count, max_kb_documents = EXCLUDED.max_kb_documents, max_file_storage_mb = EXCLUDED.max_file_storage_mb, max_file_count = EXCLUDED.max_file_count, enable_rag = EXCLUDED.enable_rag, enable_web_search = EXCLUDED.enable_web_search, enable_mcp_tools = EXCLUDED.enable_mcp_tools, status = EXCLUDED.status, sort_order = EXCLUDED.sort_order, custom_config = EXCLUDED.custom_config, benefits = EXCLUDED.benefits;
